name: coffea
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.5.0=pyhd8ed1ab_0
  - awkward=1.10.3=py311hcafe171_0
  - awkward0=0.15.5=pyhd8ed1ab_0
  - aws-c-auth=0.7.0=hbbaa140_3
  - aws-c-cal=0.6.0=h93469e0_0
  - aws-c-common=0.8.23=hd590300_0
  - aws-c-compression=0.2.17=h862ab75_1
  - aws-c-event-stream=0.3.1=h9599702_1
  - aws-c-http=0.7.11=hbe98c3e_0
  - aws-c-io=0.13.28=h3870b5a_0
  - aws-c-mqtt=0.9.0=h2e270ba_0
  - aws-c-s3=0.3.13=heb0bb06_2
  - aws-c-sdkutils=0.1.12=h862ab75_0
  - aws-checksums=0.1.16=h862ab75_1
  - aws-crt-cpp=0.21.0=h87b6960_2
  - aws-sdk-cpp=1.10.57=h7062fed_18
  - boost=1.78.0=py311h92ebd52_5
  - boost-cpp=1.78.0=h6582d0a_3
  - boost-histogram=1.3.2=py311h4dd048b_2
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py311ha362b79_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311h409f033_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - coffea=0.7.21=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.1.0=py311h9547e67_0
  - correctionlib=2.2.2=py311h4dd048b_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.2=py311h459d7ec_1
  - dask-core=2023.10.1=pyhd8ed1ab_0
  - dask-jobqueue=0.8.2=pyhd8ed1ab_0
  - distributed=2023.10.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fonttools=4.42.0=py311h459d7ec_0
  - freetype=2.12.1=hca18f0e_1
  - fsspec=2023.6.0=pyh1a96a4e_0
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.6.0=h6f12383_0
  - gsoap=2.8.123=h8dc497d_0
  - hist=2.7.1=pyhd8ed1ab_0
  - histoprint=2.4.0=pyhd8ed1ab_0
  - htcondor=10.7.1=py311h38be061_0
  - htcondor-classads=10.7.1=he155508_0
  - htcondor-utils=10.7.1=h841b71b_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - iminuit=2.22.0=py311hb755f60_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py311h4dd048b_1
  - krb5=1.21.1=h659d440_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libarrow=12.0.1=h10ac928_8_cpu
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=17_linux64_openblas
  - libcondor_utils=10.7.1=h1593839_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.2.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libgoogle-cloud=2.12.0=h840a212_1
  - libgrpc=1.56.2=h3905398_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=17_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.23.3=hd1fb520_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libthrift=0.18.1=h8fd135c_2
  - libtiff=4.5.1=h8b53f26_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvmlite=0.40.1=py311ha6695c7_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py311h9f220a4_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h459d7ec_1
  - matplotlib-base=3.7.1=py311h8597a09_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mplhep=0.3.28=pyhd8ed1ab_0
  - mplhep_data=0.0.3=pyhd8ed1ab_0
  - msgpack-python=1.0.6=py311h9547e67_0
  - munge=0.5.13=h1c5bbd1_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcb278e6_0
  - numba=0.57.1=py311h96b013e_0
  - numpy=1.24.4=py311h64a7726_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.4=hd590300_0
  - orc=1.9.0=h385abfd_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311h320fe9a_1
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=10.0.0=py311h0b84326_0
  - pip=23.2.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - psutil=5.9.5=py311h459d7ec_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=12.0.1=py311h39c9aba_8_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=2.1.1=pyhd8ed1ab_0
  - pydantic-core=2.4.0=py311h46250e7_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.4=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-htcondor=10.7.1=py311hc1a210e_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.2.0=py311h2582759_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.5.1=pyhd8ed1ab_0
  - s2n=1.3.46=h06160fa_0
  - scipy=1.11.1=py311h64a7726_0
  - scitokens-cpp=1.0.2=haea88ab_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - tblib=2.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py311h459d7ec_1
  - tqdm=4.65.2=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.14.1=h0aa22dc_2
  - uhi=0.3.3=pyhd8ed1ab_0
  - uproot=4.3.7=py311h38be061_2
  - uproot-base=4.3.7=pyhb29723e_2
  - uproot3=3.14.4=pyhd8ed1ab_0
  - uproot3-methods=0.10.1=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - voms=2.1.0rc3=h25bd2b9_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xrootd=5.6.1=py311h7c82654_0
  - xxhash=0.8.1=h0b41bf4_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py311haa97af0_2
  - zstd=1.5.2=hfc55251_7
